# NUMPY


NumPy is a array_processing Package.It provides high performence multidimentional array object 

Array is a Data structure that stores Values of same data Type. while Python list can store data of different Data Types 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

One dimensional Array

In [ ]:
lst = [1,2,3,4,5]
arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

Two dimensional Array 

In [15]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,1]
lst3 = [3,4,5,6,7]
arr1 =np.array([lst1,lst2,lst3])

In [16]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [3, 4, 5, 6, 7]])

In [18]:
arr1.shape

(3, 5)

In [19]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 3, 4],
       [5, 6, 7]])

In [20]:
aar1.reshape(5,4)

NameError: name 'aar1' is not defined

In [21]:
arr1.reshape(1,15)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 4, 5, 6, 7]])

Indexing

In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[5]

6

In [24]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,1]
lst3 = [3,4,5,6,7]
arr1 =np.array([lst1,lst2,lst3])


In [25]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [3, 4, 5, 6, 7]])

In [29]:
arr1[1:,2:4]

array([[8, 9],
       [5, 6]])

In [31]:
arr1[1:2, 1:4]

array([[7, 8, 9]])

In [32]:
arr1[:2,3:]

array([[4, 5],
       [9, 1]])

In [33]:
arr1[:2,3:]

array([[4, 5],
       [9, 1]])

In [36]:
arr1[:2, :2]

array([[1, 2],
       [6, 7]])

In [38]:
arr1[1:, :3]

array([[6, 7, 8],
       [3, 4, 5]])

In [39]:
arr1 = np.arange(0,10, step = 2)

In [40]:
arr1


array([0, 2, 4, 6, 8])

In [42]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [47]:
#copy function and broadcasting
arr[3:] =100

In [48]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [49]:
arr1 = arr

In [50]:
arr1[3:] = 500

In [51]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [ ]:
# arr copies arr1 if we change arr1. i.e because array is a refernce type

In [53]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [54]:
arr1 = arr.copy()

In [55]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [56]:
arr1[3:] = 1000
arr1

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [57]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [58]:
#conditions usefull in EDA
arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [59]:
arr>10

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [60]:
arr%10

array([1, 2, 3, 0, 0, 0, 0, 0, 0], dtype=int32)

In [61]:
arr[arr>10]

array([500, 500, 500, 500, 500, 500])

In [71]:
np.arange(0,100,2).reshape(5,10)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [72]:
np.ones((5,3),dtype= float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
#random distribution
np.random.rand(4,4)

array([[0.02385987, 0.19697594, 0.99201498, 0.11215348],
       [0.00458951, 0.96822723, 0.61466229, 0.95322323],
       [0.00957458, 0.73726411, 0.50088004, 0.96065614],
       [0.70392397, 0.83079307, 0.64322628, 0.57746333]])

In [78]:
#standard Normal distribution
np.random.randn(3,3)

array([[-1.48654473, -0.83431599,  0.39508315],
       [-0.82884737,  0.19344919, -0.44903257],
       [-0.42938518,  0.04554729, -0.27868124]])

In [80]:
np.random.randint(0,100,8).reshape(2,4)

array([[39, 59, 63, 66],
       [63, 59, 53, 74]])